### ISSUE TITLE
In order to check out, users must be logged in, application should allow users to register and log in once they’re registered. Users should remain logged in even if they close the application until JWT expires.

### ISSUE THREAD

**Issue by lasalgado** [rene-ph/store-react#2]
- [x] {HOST}/login/
- [x] Formulario para inicio de sesion con email y contraseña
- [x] Llamar EP para realizar el login y guardar token para la app
- [x] Llamar EP con los datos del usuario y actualizar barra superior con info del usuario
- [x] Validaciones del formulario

- [x] {HOST}/register/
- [x] Formulario para pedir displayName, email y correo
- [x] Llamar registro desde el EP y mostrar mensajes de error o exito
- [x] Boton de redigir a pantalla principal o iniciar sesion
- [x] Validaciones del formulario

( Register.png and SignIn.png)

**Comment by rhinojosadev** [comment]
<img width="642" alt="SignIn" src="https://user-images.githubusercontent.com/3522527/131391826-7c51a299-10e7-4641-b36d-f98317367b54.png">
<img width="799" alt="Register" src="https://user-images.githubusercontent.com/3522527/131391852-c2d14dde-03d6-4695-989d-907fa702defb.png">
